# Generated by Django 3.0.7 on 2023-10-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20231028_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='stock_images/'),
        ),
    ]
