# Generated by Django 3.0.7 on 2023-10-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='image',
        ),
    ]
