# Generated by Django 3.0.7 on 2023-10-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stocknotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='notification_threshold',
        ),
        migrations.DeleteModel(
            name='StockNotification',
        ),
    ]
