# Generated by Django 3.0.7 on 2023-10-30 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
