# Generated by Django 3.0.7 on 2023-10-31 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20231031_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='contonaire',
        ),
        migrations.DeleteModel(
            name='Contonaire',
        ),
    ]
