# Generated by Django 3.0.7 on 2023-11-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stock_container_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='container_name',
        ),
    ]
