# Generated by Django 3.0.7 on 2023-11-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20231101_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
