# Generated by Django 3.0.7 on 2023-11-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20231110_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='square_meter',
        ),
        migrations.AddField(
            model_name='stock',
            name='cubic_meter',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
