# Generated by Django 3.0.7 on 2023-11-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_remove_stock_qt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='qT',
            field=models.IntegerField(default=1),
        ),
    ]
