# Generated by Django 3.0.7 on 2023-11-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_stock_qt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='qT',
        ),
    ]
