# Generated by Django 3.0.7 on 2024-03-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auto_20240325_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='length_a',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='width_a',
        ),
    ]
