# Generated by Django 3.0.7 on 2023-11-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_saleitem_cubic_meter_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='cubic_meter_sold',
        ),
    ]
