# Generated by Django 3.0.7 on 2023-11-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_saleitem_cubic_meter_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cubic_meter',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price_per_cubic_meter',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
