# Generated by Django 3.0.7 on 2023-11-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20231112_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='cubic_meter',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='price_per_cubic_meter',
        ),
    ]
