# Generated by Django 3.0.7 on 2023-11-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20231112_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cubic_meter',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='perprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
