# Generated by Django 3.0.7 on 2023-11-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20231121_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='sale_type',
            field=models.CharField(default='quantity', max_length=20),
        ),
    ]
