# Generated by Django 3.0.7 on 2023-11-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_offer_offerdetails_offeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
