# Generated by Django 3.0.7 on 2023-11-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_offer_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='total_price',
        ),
    ]
