# Generated by Django 3.0.7 on 2023-11-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20231129_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
