# Generated by Django 3.0.7 on 2023-11-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20231129_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
