# Generated by Django 3.0.7 on 2023-12-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20231202_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeritem',
            name='sale_type',
            field=models.CharField(choices=[('quantity', 'Quantity'), ('cubic_meter', 'Cubic Meter')], default='cubic_meter', max_length=20),
        ),
    ]
