# Generated by Django 3.0.7 on 2023-12-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_offeritem_sale_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeritem',
            name='sale_type',
        ),
        migrations.AlterField(
            model_name='offer',
            name='sale_type',
            field=models.CharField(choices=[('quantity', 'Quantity'), ('cubic_meter', 'Cubic Meter')], default='quantity', max_length=20),
        ),
    ]
