# Generated by Django 3.0.7 on 2023-12-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_offeritem_sale_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeritem',
            name='sale_type',
        ),
    ]
