# Generated by Django 3.0.7 on 2023-12-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_remove_offeritem_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebill',
            name='generate_bon_de_livraison',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salebill',
            name='generate_facture',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='sale_type',
            field=models.CharField(choices=[('quantity', 'Sale per Quantity'), ('cubic_meter', 'Sale per Cubic Meter')], default='quantity', max_length=20),
        ),
    ]
