# Generated by Django 3.0.7 on 2023-12-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_auto_20231205_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salebill',
            old_name='generate_facture',
            new_name='generate_facture_bon_livrasion',
        ),
    ]
