# Generated by Django 3.0.7 on 2023-12-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_auto_20231205_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='generate_bon_de_livraison',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='generate_facture_bon_livrasion',
        ),
        migrations.AddField(
            model_name='salebill',
            name='extra_options',
            field=models.CharField(choices=[('facture_bon_livraison', 'Facture and Bon de Livraison'), ('bon_de_livraison', 'Bon de Livraison')], default='bon_de_livraison', max_length=25),
        ),
    ]
