# Generated by Django 3.0.7 on 2023-12-05 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_facturebill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FactureBill',
        ),
    ]
