# Generated by Django 3.0.7 on 2023-12-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_delete_facturebill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='facture_no',
        ),
    ]
