# Generated by Django 3.0.7 on 2023-12-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_salebill_facture_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='facture_numero',
        ),
    ]
