# Generated by Django 3.0.7 on 2023-12-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_salebill_numero_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastFactureNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_facture_number', models.IntegerField(default=0)),
            ],
        ),
    ]
