# Generated by Django 3.0.7 on 2023-12-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_lastfacturenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='gstin',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='per_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='gstin',
            field=models.CharField(max_length=30),
        ),
    ]
