# Generated by Django 3.0.7 on 2023-12-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_auto_20231219_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='gstin',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='gstin',
            field=models.CharField(max_length=15),
        ),
    ]
