# Generated by Django 3.0.7 on 2023-12-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0042_auto_20231219_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
