# Generated by Django 3.0.7 on 2023-12-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0044_auto_20231219_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='gstin',
            field=models.CharField(max_length=30),
        ),
    ]
