# Generated by Django 3.0.7 on 2023-12-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0046_auto_20231219_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='cubic_meter',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='per_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30),
        ),
    ]
