# Generated by Django 3.0.7 on 2024-02-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0048_auto_20240221_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='gstin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
