# Generated by Django 3.0.7 on 2024-02-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0049_auto_20240221_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='offer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='offer',
            name='gstin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='offer',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
