# Generated by Django 3.0.7 on 2024-02-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0053_lastbillnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastBillNumber',
        ),
    ]
