# Generated by Django 3.0.7 on 2024-02-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0054_delete_lastbillnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastBillNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_bill_number', models.IntegerField(default=0)),
            ],
        ),
    ]
