# Generated by Django 3.0.7 on 2024-02-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0055_lastbillnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastBillNumber',
        ),
    ]
