# Generated by Django 3.0.7 on 2024-03-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0056_delete_lastbillnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='sale_type',
        ),
        migrations.AddField(
            model_name='offeritem',
            name='sale_type',
            field=models.CharField(choices=[('quantity', 'Quantity'), ('cubic_meter', 'Cubic Meter')], default='quantity', max_length=20),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
    ]
