# Generated by Django 3.0.7 on 2024-03-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0057_auto_20240305_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeritem',
            name='sale_type',
        ),
        migrations.AddField(
            model_name='offer',
            name='sale_type',
            field=models.CharField(choices=[('quantity', 'Quantity'), ('cubic_meter', 'Cubic Meter')], default='quantity', max_length=20),
        ),
    ]
