# Generated by Django 3.0.7 on 2024-03-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0059_auto_20240306_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='sale_type',
            field=models.CharField(choices=[('quantity', 'Sale per Quantity'), ('cubic_meter', 'Sale per Cubic Meter'), ('both', 'Both Quantity and Cubic Meter')], default='quantity', max_length=20),
        ),
    ]
