# Generated by Django 3.0.7 on 2024-03-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0060_auto_20240306_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='perprice',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
