# Generated by Django 3.0.7 on 2024-05-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0063_auto_20240401_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
