# Generated by Django 3.0.7 on 2024-05-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0064_auto_20240506_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salebill',
            old_name='time',
            new_name='date',
        ),
    ]
