# Generated by Django 3.0.7 on 2024-05-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0065_auto_20240506_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='date',
        ),
        migrations.AddField(
            model_name='salebill',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
