# Generated by Django 3.0.7 on 2024-05-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0066_auto_20240506_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
