# Generated by Django 3.0.7 on 2024-05-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0067_auto_20240506_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
