# Generated by Django 3.0.7 on 2024-05-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0068_auto_20240506_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
